services:
  mongo:
    image: mongo:8
    container_name: todoe-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: todoe
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats:latest
    container_name: todoe-nats
    restart: unless-stopped
    ports:
      - "4222:4222"

volumes:
  mongo-data:
